gradinghelper/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('submissions.urls')),
    path('admin/', admin.site.urls),
]

submissions/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth

from . import views

app_name = 'submissions'


if hasattr(auth, 'LoginView'):
    auth_login = auth.LoginView.as_view()
    auth_logout = auth.LogoutView.as_view()
else:
    auth_login = auth.login
    auth_logout = auth.logout


urlpatterns = [
    path('auth/', include('django_lti_login.urls')),  # XXX: django-lti-login

    path('auth/login/', auth_login, {'template_name': 'login.html'},
         name='login'),

    path('auth/logout/', auth_logout, {'template_name': 'logged_out.html'},
         name='logout'),

    path('', views.IndexView.as_view(),
         name='index'),

    path('courses/', views.CourseListView.as_view(),
         name='courses'),

    path('courses/<int:pk>-<int:course_id>/exercises/',
         views.ExerciseListView.as_view(),
         name='exercises'),

    path('courses/<int:pk>-<int:course_id>/exercises/update/',
         views.GetExercisesRedirectView.as_view(),
         name='get_exercises'),

    path('courses/<int:pk>-<int:course_id>/exercises/grading_on/',
         views.EnableExerciseGradingRedirectView.as_view(),
         name='grading_on'),

    path('courses/<int:pk>-<int:course_id>/exercises/<int:pk_e>/update/',
         views.UpdateExerciseInGradingView.as_view(),
         name='update_exercise'),

    path('courses/<int:pk>-<int:course_id>/exercises/<int:pk_e>/grading_off/',
         views.DisableExerciseGradingRedirectView.as_view(),
         name='grading_off'),

    path('courses/<int:pk>-<int:course_id>/exercises/<int:pk_e>/handle_error/',
         views.HandleExerciseErrorRedirectView.as_view(),
         name='handle_error'),

    path('exercises/<int:pk>-<int:exercise_id>/submissions/update/',
         views.UpdateSubmissionsRedirectView.as_view(),
         name='update_submissions'),

    path('exercises/<int:pk>-<int:exercise_id>/submissions/grading',
         views.GradingListView.as_view(),
         name='grading'),

    path('exercises/<int:pk>-<int:exercise_id>/submissions/all/',
         views.SubmissionsFormView.as_view(),
         name='submissions'),

    path('exercises/<int:pk>-<int:exercise_id>/submissions/<int:pk_s>-<int:sub_id>/',
         views.FeedbackView.as_view(),
         name='feedback'),

    path('exercises/<int:pk>-<int:exercise_id>/submissions/release/',
         views.ReleaseFeedbacksRedirectView.as_view(),
         name='release'),

    path('exercises/<int:pk>-<int:exercise_id>/submissions/batch_assess/',
         views.BatchAssessRedirectView.as_view(),
         name='batch_assess'),

    path('exercises/<int:pk>-<int:exercise_id>/submissions/setgrader/',
         views.SetGraderRedirectView.as_view(),
         name='set_grader'),

    path('exercises/<int:pk>-<int:exercise_id>/submissions/json/',
         views.CreateJsonFromFeedbacksView.as_view(),
         name='json'),

    path('exercises/<int:pk>-<int:exercise_id>/submissions/undo_release/',
         views.UndoLatestReleaseRedirectView.as_view(),
         name='undo'),

    path('exercises/<int:pk>-<int:exercise_id>/submissions/csv/',
         views.DownloadCsvView.as_view(),
         name='csv'),
]

submissions/views.py
"""
Module comment here
"""

import csv
import logging
import requests

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.forms import modelformset_factory
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models import Course, Exercise, Feedback, Student
import submissions.forms as forms
import submissions.utils as utils


view_logger = logging.getLogger(__name__)


class ExerciseMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "exercise_id" in self.kwargs:
            exercise = get_object_or_404(Exercise, pk=self.kwargs["pk"])
            context["exercise"] = exercise
            context["course"] = exercise.course
            context["user_is_teacher"] = exercise.course.is_teacher(
                self.request.user
            )
            context["feedback_count"] = exercise.feedback_set.all().count()
            context["ready_count"] = exercise.feedback_set.filter(
                status=Feedback.READY
            ).count()
            context["grader_lang_en"] = exercise.feedback_set.filter(
                grader_lang_en=True
            ).count()

        return context


class IndexView(LoginRequiredMixin, generic.RedirectView):
    """
    Aplikaation juuriosoite, uudelleenohjaa kurssilistaukseen.
    """
    pattern_name = "submissions:courses"


class CourseListView(LoginRequiredMixin, generic.ListView):
    """
    Listaa kaikki kurssit, joihin käyttäjä on liitetty.
    return: Lista käyttäjän kursseista.
    """
    model = Course
    template_name = "submissions/courses.html"
    context_object_name = "courses"
    
    def get(self, request, *args, **kwargs):

        #TODO: Show all courses if user is superuser
        self.object_list = Course.objects.filter(
            Q(
                base_course__assistants=request.user
            ) | Q(
                base_course__teachers=request.user
            )
        ).distinct()

        return self.render_to_response(self.get_context_data())
        
        
class ExerciseListView(LoginRequiredMixin, generic.ListView):
    """
    Lists the exercises which have been set for grading.
    """
    model = Exercise
    template_name = "submissions/exercises.html"
    context_object_name = "exercises"
    
    def get(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=kwargs["pk"])

        if not course.is_staff(request.user):
            raise PermissionDenied

        self.object_list = self.get_queryset().filter(
            course=course).filter(in_grading=True)

        # There are two tabs in the template and this
        # information tells which one to show.
        if "show_set_grading" in request.session:
            show_set_grading = request.session["show_set_grading"]
            request.session["show_set_grading"] = False
        else:
            show_set_grading = False

        context = self.get_context_data(
            user=request.user,
            course=course,
            show_set_grading=show_set_grading
        )

        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if not kwargs["course"].is_teacher(kwargs["user"]):
            context["show_set_grading"] = False

        else:
            context["user_is_teacher"] = True
            context["form"] = forms.ExerciseSetGradingForm(
                course=kwargs["course"]
            )
            context["error_handler"] = forms.ErrorHandlerForm()

            for exercise in self.object_list:
                exercise.form = forms.ExerciseUpdateForm(
                    instance=exercise, course=kwargs["course"]
                )

            # If user is teacher and exercise list is empty
            # the ExerciseSetGradinForm will be viewed.
            if self.object_list.count() == 0:
                context["show_set_grading"] = True

        return context


class GetExercisesRedirectView(LoginRequiredMixin, generic.RedirectView):
    """
    Retrieve exercises of the specific course from Plussa.
    """
    pattern_name = "submissions:exercises"

    def post(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=kwargs["pk"])

        # TODO: voiko jotain mennä pieleen, että tehtäviä ei päivitetäkään?
        # get exercises from Plussa and save them to database
        utils.get_exercises(course)

        # Information passed to template which tab to show
        request.session["show_set_grading"] = True
        messages.success(request, "Course content updated")

        return self.get(request, *args, **kwargs)


class UpdateSubmissionsRedirectView(LoginRequiredMixin, generic.RedirectView):
    """
    Lisätään/päivitetään tehtävän palautukset tietokantaan.
    """

    # TODO: muuttaa tietokannan tilaa, joten muuta postiksi
    def get(self, request, *args, **kwargs):
        exercise = get_object_or_404(Exercise, pk=kwargs["pk"])
        try:
            utils.update_submissions(exercise)
            messages.success(request, "Submissions updated")
        except requests.HTTPError as e:
            messages.error(request, f"Failed to retrieve submissions: {e}")

        return super().get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        url = self.request.META.get("HTTP_REFERER", "")
        return url


class EnableExerciseGradingRedirectView(LoginRequiredMixin,
                                        generic.RedirectView):
    """
    Handles the request to enable exercise grading with submitted settings.
    """
    pattern_name = "submissions:exercises"
    
    def post(self, request, *args, **kwargs):
        exercise = get_object_or_404(Exercise, pk=request.POST["name"])
        form = forms.ExerciseSetGradingForm(request.POST, request.FILES,
                                            instance=exercise)

        if form.is_valid():
            exercise = form.save(commit=False)
            exercise.in_grading = True
            form.save_m2m()
            graders_all = \
                exercise.graders.count() + exercise.graders_en.count()

            if exercise.num_of_graders is None or \
                    exercise.num_of_graders < graders_all:
                exercise.num_of_graders = graders_all

            exercise.total_max_points = utils.get_json(
                exercise.api_url, exercise.course.api_token
            )["max_points"]

            exercise.save(update_fields=["min_points", "max_points",
                                         "total_max_points", "add_penalty",
                                         "add_auto_grade", "work_div",
                                         "num_of_graders", "feedback_base_fi",
                                         "feedback_base_en", "in_grading"])

            messages.success(request, "Exercise added for grading")

        else:
            #messages.error(self.request, "Invalid fields:")

            for error in form.errors:
                messages.error(self.request, form.errors[error])

            # Information passed to template which tab to show
            request.session["show_set_grading"] = True

        return self.get(request, *args, **kwargs)
        

class UpdateExerciseInGradingView(LoginRequiredMixin, generic.edit.UpdateView):
    """
    Handle the request to update exercise grading settings.
    """
    model = Exercise
    pk_url_kwarg = "pk_e"
    slug_field = "exercise_id"
    slug_url_kwarg = "exercise_id"
    query_pk_and_slug = True
    form_class = forms.ExerciseUpdateForm

    def get_success_url(self):
        return reverse(
            "submissions:exercises", kwargs={
                "pk": self.kwargs["pk"],
                "course_id": self.kwargs["course_id"]
            }
        )

    def form_valid(self, form):
        self.object = form.save()

        all_graders = \
            self.object.graders.count() + self.object.graders_en.count()

        if self.object.num_of_graders is None or \
                self.object.num_of_graders < all_graders:
            self.object.num_of_graders = all_graders
            self.object.save()

        # Minimum points of accepted submission have been increased.
        # Remove submissions with points lesser than new limit but
        # only if the feedback status is still template.
        self.object.feedback_set.filter(
            status=Feedback.BASE,
            auto_grade__lt=self.object.min_points
        ).delete()

        # Maximum points for auto grade have been decreased.
        # Remove submissions with points greater than new limit but
        # only if the feedback status is still template.
        if self.object.max_points is not None:
            self.object.feedback_set.filter(
                status=Feedback.BASE,
                auto_grade__gt=self.object.max_points
            ).delete()

        # Update feedback base if it exists. Update is done only
        # if Feedback object's status is Feedback.BASE
        if self.object.feedback_base_fi or self.object.feedback_base_en:
            for feedback in self.object.feedback_set.all():
                utils.add_feedback_base(self.object, feedback)

        messages.success(self.request, "Changes saved successfully")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Invalid fields:")

        for error in form.errors:
            messages.error(self.request, form.errors[error])

        return HttpResponseRedirect(self.get_success_url())


class DisableExerciseGradingRedirectView(LoginRequiredMixin,

submissions/templates/submissions/exercises.html
{% extends 'submissions/courses.html' %}

{% load bootstrap4 %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Exercises" "submissions:exercises" course.id course.course_id %}
{% endblock %}

{% block coursename %} {{ course.name }} {% endblock %}

{% block content %}

  <div class="col-md-8 offset-md-2">

    <ul class="nav nav-tabs m-4">
      <li class="nav-item">
        <a class="nav-link {% if not show_set_grading %} active {% endif %}"
           data-toggle="tab" href="#exercises">
          Exercises for grading
        </a>
      </li>
      {% if user_is_teacher %}
        <li class="nav-item">
          <a class="nav-link {% if show_set_grading %} active {% endif %}" data-toggle="tab"
             href="#set_grading">
            Add exercises
          </a>
        </li>
      {% endif %}
    </ul>

    <div class="tab-content">

      <div class="tab-pane fade {% if not show_set_grading %} show active {% endif %}" id="exercises">
        <div class="card card-body bg-light">

          {% for exercise in exercises %}

            <ul class="list-group exercises">
              <li class="list-group-item {{ exercise.exercise_id }}">
                <div class="d-flex align-items-center">

                  <div class="flex-grow-1">
                    {{ exercise }}
                  </div>


                  <div class="ml-auto">

                    <a class="btn btn-primary btn-sm" href="{% url 'submissions:grading' exercise.id exercise.exercise_id %}" role="button">
                      My grading list
                    </a>

                    <a class="btn btn-primary btn-sm" href="{% url 'submissions:submissions' exercise.id exercise.exercise_id %}" role="button">
                      All submissions
                    </a>

                {% if user_is_teacher %}
                    <button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#{{ exercise.exercise_id }}">
                      Settings
                      {% if exercise.error_state %}
                        <span class="badge badge-danger">Error</span>
                      {% endif %}
                    </button>

                  </div> <!-- buttons -->
                </div> <!-- d-flex -->


                <div class="collapse mt-4" id="{{ exercise.exercise_id }}">

                    {% if exercise.error_state %}
                    <div class="card card-body bg-light">
                      <div class="alert alert-danger" role="alert">
                        <p>{{ exercise.error_state }}</p>
                        <hr>
                        <p>This is probably caused by a temporary problem if
                        you have not modified exercise configuration in
                        Plussa. Select "Ignore warning...".
                        <hr>
                        <p>Sometimes reason could be that this particular
                        exercise ID doesn't exist in Plussa anymore. If you
                        are sure about it, select "Delete this exercise..."
                      </div>
                      <form action="{% url 'submissions:handle_error' course.id course.course_id exercise.id %}" method="post">
                        {% csrf_token %}
                        {% bootstrap_form error_handler %}
                        <button type="submit" class="btn btn-primary">
                          OK
                        </button>
                      </form>
                    </div>
                    {% endif %}


                  <div class="card card-body bg-light">
                    <form action="{% url 'submissions:update_exercise' course.id course.course_id exercise.id %}" method="post" class="form" enctype="multipart/form-data">
                      {% csrf_token %}
                      {% bootstrap_form exercise.form %}
                      <button class="btn btn-danger" type="button" data-toggle="collapse" data-target="#delete_{{ exercise.exercise_id }}">
                        Delete
                      </button>
                      <button type="submit" class="btn btn-success float-right">
                        Update
                      </button>
                    </form>

                  </div>
                </div> <!-- collapse -->


                <div class="collapse mt-4" id="delete_{{ exercise.exercise_id }}">

                  <div class="alert alert-danger" role="alert">
                    This exercise and all assessments related to it will be
                    removed. Are you sure?
                  </div>

                  <form action="{% url 'submissions:grading_off' course.id course.course_id exercise.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#delete_{{ exercise.exercise_id }}">
                      Cancel
                    </button>
                    <button type="submit" class="btn btn-danger float-right">
                      Delete
                    </button>
                  </form>

                </div> <!-- collapse -->

                {% endif %}

              </li>
            </ul>

          {% empty %}
            <div class="alert alert-info" role="alert">
              No exercises added yet
            </div>
          {% endfor %}

        </div> <!-- tab-pane -->
      </div> <!-- card -->

      {% if user_is_teacher %}
        <div class="tab-pane fade {% if show_set_grading %} show active {% endif %}" id="set_grading">
          <div class="card card-body m-2 bg-light">

            <form action="{% url 'submissions:get_exercises' course.id course.course_id %}" method="post" class="form">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary btn-lg m-4">Update course content</button>
              <small>Click the button to update exercise list if something seems to be missing.</small>
            </form>

            <form action="{% url 'submissions:grading_on' course.id course.course_id %}" method="post" class="form" enctype="multipart/form-data">
              {% csrf_token %}
              {% bootstrap_form form %}
              <button type="submit" class="btn btn-primary">Add</button>
            </form>

          </div> <!-- tab-pane -->
        </div> <!-- card -->
      {% endif %}

    </div> <!-- tab-content -->

  </div> <!-- column -->

{% endblock %}

submissions/templates/submissions/feedback.html
{% extends 'submissions/base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div class="col-md-6">
    <a href="{{ sub_url }}">{{ sub_url }}</a>
    <pre>{{ sub_code }}</pre>
  </div>
  
  
  <div class="col-md-6">
    <form action="{% url 'submissions:feedback' exercise sub_id %}" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
  
{% endblock %}

submissions/templates/submissions/gradinglist.html
{% extends 'submissions/exercises.html' %}

{% load bootstrap4 %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "My grading list" "submissions:grading" exercise.id exercise.exercise_id %}
{% endblock %}

{% block content %}

  <div class="col-md-6 offset-md-3">

    <ul class="nav nav-tabs m-4">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#my_grading_list">
          My grading list
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " data-toggle="tab"
           href="#no_grader">
          Submissions without grader
        </a>
      </li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane fade show active" id="my_grading_list">
        <h4> {{ exercise.name }} </h4>

        <h6> My work count: {{ my_ready_count }} / {{ my_feedback_count }} </h6>
        <h6> Total work count: {{ ready_count }} / {{ feedback_count }} </h6>

        {% if gradinglist %}
          <table class="table table-bordered table-sm table-hover my-4">
            <thead class="thead-light">
              <tr>
                <th scope="col">Submission Id</th>
                <th scope="col">Student Id and email</th>
                <th scope="col">Status</th>
                <th scope="col">Grade</th>

              </tr>
            </thead>

            <tbody>
              {% for sub in gradinglist %}
              <tr>
                <td class="align-middle">
                  <a href="{%url 'submissions:feedback' sub.exercise.id sub.exercise.exercise_id sub.id sub.sub_id %}">
                    {{ sub }}
                  </a>
                </td>

                <td class="align-middle">
                  {% for student in sub.students.all %}
                    <div>{{ student }}</div>
                  {% endfor %}
                </td>

                <td class="align-middle">
                  {% if sub.released %}
                    <div class="alert alert-success" role="alert">
                      RELEASED
                    </div>
                  {% elif sub.status == sub.READY %}
                    <div class="alert alert-warning" role="alert">
                      READY
                    </div>
                  {% elif sub.status == sub.DRAFT %}
                    <div class="alert alert-danger" role="alert">
                      DRAFT
                    </div>
                  {% else %}
                    <div class="alert alert-info" role="alert">
                      UNSTARTED
                    </div>
                  {% endif %}
                </td>

                <td class="text-center align-middle">
                  {{ sub.staff_grade }}
                </td>


              </tr>
            {% endfor %}
            </tbody>
          </table>
        {% else %}
          <div class="alert alert-info" role="alert">
            Grading list is empty
          </div>
        {% endif %}


        <div class="d-flex justify-content-around mt-2">
          {% if gradinglist %}
          <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#release">
            Post assessments to Plussa
          </button>
          <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#mass_grading">
            Batch assess
          </button>
          {% endif %}
          <a class="btn btn-primary" href="{% url 'submissions:update_submissions' exercise.id exercise.exercise_id %}" role="button">
            Get latest submissions
          </a>
        </div> <!-- data-toggle buttons -->

        <div class="collapse mt-4" id="release">
          <div class="alert alert-danger" role="alert">
            <p>All assessments with status READY will be posted to Plussa.
            Feedbacks and grades will become visible to students. THIS CANNOT
            BE CANCELLED. This could take a while if there are a lot of
            assessments to post. Choose RELEASE to continue.

            <p>Kaikki READY-tilassa olevat palautteet lähetetään Plussaan.
            Tämän jälkeen palautteet ja pisteet ovat opiskelijoiden nähtävillä
            Plussassa. Toimintoa ei voi peruuttaa. Toiminnon suorittaminen
            kestää kauan, jos julkaistavaa on paljon.
            Jatka valitsemalla RELEASE.
          </div>
          <form method="post" action="{% url 'submissions:release' exercise.id exercise.exercise_id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">
              RELEASE
            </button>
          </form>
        </div> <!-- collapse release -->
        
        <div class="collapse mt-4" id="mass_grading">
          <div class="alert alert-info" role="alert">
            Assess all submissions with the same grade. Grade is applied only
            if the status of the assessment is UNSTARTED. A brief feedback can
            also be added but it is optional. Status of the assessment will
            be set to READY. THIS CANNOT BE CANCELLED.
          </div>
          <form class="form-control" method="post" action="{% url 'submissions:batch_assess' exercise.id exercise.exercise_id %}">
            {% csrf_token %}
            {% bootstrap_form batch_assess_form %}
            <input type="submit" value="Batch assess">
          </form>
        </div> <!-- collapse mass_grading -->


      </div> <!-- tab-pane grading_list -->



      <div class="tab-pane fade" id="no_grader">
        <h4> {{ exercise.name }} </h4>

        <!-- formset.total_form_count saadaan lomakkeen objektien määrä-->

        {% if formset.forms %}
          <form method="post" action="{% url 'submissions:set_grader' exercise.id exercise.exercise_id %}">
            {% csrf_token %}
            {{ formset.management_form }}

            <table class="table table-bordered table-sm table-hover">
              <thead class="thead-light">
                <tr>
                    <th scope="col">Submission Id</th>
                    <th scope="col">Student Id and email</th>
                    <th scope="col">Select</th>
                </tr>
              </thead>

              <tbody>
                {% for form in formset %}
                <tr>
                  {{ form.id }}
                  <td>
                    {{ form.instance.sub_id }}
                  </td>

                  <td>
                    {% for student in form.instance.students.all %}
                      <div>
                        {{ student }}
                      </div>
                    {% endfor %}
                  </td>

                  <td>
                    {{ form.check_this }}
                  </td>

                </tr>
                {% endfor %}
              </tbody>
            </table>

            <button type="submit" class="btn btn-primary">Add to my grading list</button>

          </form>

        {% else %}

          <div class="alert alert-info" role="alert">
            No submissions available
          </div>

        {% endif %}
      </div> <!-- tab-pane no_grader -->
    </div> <!-- tab-content -->


  </div> <!-- column -->

{% endblock %}

submissions/templates/submissions/submissions_form.html
{% extends 'submissions/exercises.html' %}

{% load bootstrap4 %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "All submissions" "submissions:submissions" exercise.id exercise.exercise_id %}
{% endblock %}

{% block content %}

  <div class="col-md-8 offset-md-2">

    <h2> All submissions </h2>
    <h4> {{ exercise.name }} </h4>

    <h6> Work count: {{ ready_count }} / {{ feedback_count }} </h6>
    <h6> English: {{ grader_lang_en }} / {{ feedback_count }} </h6>

    <div class="d-flex justify-content-around m-4">
    {% if user_is_teacher %}
      {% if form.forms %}
        <form method="post" action="{% url 'submissions:json' exercise.id exercise.exercise_id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">
            Create json for Plussa batch assess tool
          </button>
        </form>
        <form method="post" action="{% url 'submissions:undo' exercise.id exercise.exercise_id%}">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">
            Restore status RELEASED -> READY
          </button>
        </form>

        <a class="btn btn-primary" href="{% url 'submissions:csv' exercise.id exercise.exercise_id %}" role="button">
          Work list as csv file
        </a>

      {% endif %}

      <a class="btn btn-primary" href="{% url 'submissions:update_submissions' exercise.id exercise.exercise_id %}" role="button">
        Get latest submissions
      </a>

    {% endif %}
    </div> <!-- d-flex -->


    {% if form.forms %}
        <form method="post" action="{% url 'submissions:submissions' exercise.id exercise.exercise_id %}">
          {% csrf_token %}
          {{ form.management_form }}

          <table class="table table-bordered table-hover table-sm">
            <thead class="thead-light">
              <tr>
                  <th scope="col">Submission Id</th>
                  <th scope="col">Student Id and email</th>
                  <th scope="col">Status</th>
                  <th scope="col">Grader</th>
              </tr>
            </thead>

            <tbody>
              {% for sub_form in form %}
              <tr>
                <td>
                  {{ sub_form.id }}
                  <a href="{%url 'submissions:feedback' exercise.id exercise.exercise_id sub_form.instance.id sub_form.instance.sub_id %}">
                    {{ sub_form.instance.sub_id }}
                  </a>
                </td>

                <td>
                  {% for student in sub_form.instance.students.all %}
                    <div>
                        {{ student }}
                    </div>

                  {% endfor %}
                </td>

                <td>
                    {% if sub_form.instance.released %}
                      <div class="alert alert-success" role="alert">
                        RELEASED
                      </div>
                    {% elif sub_form.instance.status == sub_form.instance.READY %}
                      <div class="alert alert-warning" role="alert">
                        READY
                      </div>
                    {% elif sub_form.instance.status == sub_form.instance.DRAFT %}
                      <div class="alert alert-danger" role="alert">
                        DRAFT
                      </div>

                    {% else %}
                      <div class="alert alert-info" role="alert">
                        UNSTARTED
                      </div>
                    {% endif %}
                </td>

                <td>
                  {{ sub_form.grader }}
                </td>

              </tr>
            {% endfor %}
            </tbody>
          </table>

          <button type="submit" class="btn btn-primary">Save</button>
        </form>

    {% endif %}


  </div> <!-- column -->
  
{% endblock %}